# Generated by Django 5.2.4 on 2025-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.TextField(blank=True, help_text='Specific address or location details', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('environment', 'Environment'), ('public_safety', 'Public Safety'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
