# Generated by Django 5.2.5 on 2025-09-01 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_district_alter_user_ds_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_successful', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('citizen', 'Citizen'), ('prime_minister', 'Prime Minister'), ('grama_niladhari', 'Grama Niladhari'), ('national_ministry', 'National Ministry'), ('district_secretary', 'District Secretary'), ('provincial_ministry', 'Provincial Ministry'), ('divisional_secretary', 'Divisional Secretary')], default='citizen', max_length=20),
        ),
        migrations.CreateModel(
            name='GoogleAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('google_auth', 'Google Authenticator')], max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('secret_key', models.CharField(blank=True, max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
